Seemingly unrelated changes generated bug
zipeducation/buildspace-projects pull request #276
Opened 2021-10-27 18:50 UTC by 7i7o

I saw a lot of projects showing the loading indicator in a loop when the browser didn't have the ethereum object or the user didn't connect any wallet

This bug was generated from code at the beggining of the UI section + adding the LoadingIndicator at the end of the project

![Screen Shot 2021-10-27 at 15 49 37](https://user-images.githubusercontent.com/84824996/139128272-a0bee785-7124-4f65-84f2-46c23a1b9e95.png)

2021-10-30 02:16 UTC, 7i7o commented
Hi @adilanchian !

I already merged with buildspace:main (was only 2 commits behind that had no connection with this issue).
Before i started, i made sure of fetching the latest from your main. I even edited the whole thing in the github page so i was sure i didn't mess up. lol

Let me know if i am missing something

Eternally thankful for all the knowledge you guys are sharing!!!

2021-11-01 14:38 UTC, adilanchian requested changes
Thanks for checking in on the latest for me :)

Left some comments! Let me know if you have any questions

2021-11-01 14:38 UTC, adilanchian commented on NFT_Game/en/Section_4/Lesson_1_Finishing_Touches_UI.md
> +
So this is actually part of the `🔁 Adding loading indicators to App.js.` section! I don't think we need to make an entirely new section for this. 

Can you make the changes in that section instead?

2021-11-01 14:38 UTC, adilanchian commented on NFT_Game/en/Section_3/Lesson_2_Building_Connect_Wallet_Button.md
> +        }
also - I think you accidentally added a tab here - can you please revert?

2021-11-01 14:49 UTC, 7i7o commented on NFT_Game/en/Section_4/Lesson_1_Finishing_Touches_UI.md
> +
Of course. As soon as I get home, I’ll merge it :)

2021-11-01 14:53 UTC, 7i7o commented on NFT_Game/en/Section_3/Lesson_2_Building_Connect_Wallet_Button.md
> +        }
This was actually on purpose, so it stays inside the “else” clause. 
Look in the previous JavaScript block, in the same lesson, that part of the code is inside the “else”.
I thought that you guys had unintentionally changed it 🤣

2021-11-01 15:26 UTC, adilanchian commented on NFT_Game/en/Section_3/Lesson_2_Building_Connect_Wallet_Button.md
> +        }
Haha AHH SHIT. Ya nice catch I totally didn't notice this 😅

ROGER. Can you do me a huge favor - could you make sure this code block is updated everywhere it is used in this project? I'll do a double check as well :)

2021-11-01 15:48 UTC, 7i7o commented on NFT_Game/en/Section_3/Lesson_2_Building_Connect_Wallet_Button.md
> +        }
Sure. No problem. As soon as I get my hands on the computer I’ll check both 😊

2021-11-01 19:34 UTC, 7i7o commented on NFT_Game/en/Section_4/Lesson_1_Finishing_Touches_UI.md
> +
Done, included this code block at the end of the the "🔁 Adding loading indicators to App.js." section.

2021-11-01 19:34 UTC, 7i7o commented on NFT_Game/en/Section_3/Lesson_2_Building_Connect_Wallet_Button.md
> +        }
Just checked it and this was the last time this function was shown (until that code block i had to add on the other comment thread).

2021-11-02 13:55 UTC, adilanchian commented
EPIC. Thanks for working with me on this :). 

Nice work ✨

2021-11-02 13:55 UTC, merged

2021-11-02 13:55 UTC, adilanchian commented
@all-contributors please add @7i7o for doc