Minor Typo_s
zipeducation/buildspace-projects pull request #33
Opened 2021-09-26 23:49 UTC by sieis

A few _super_small typos in the text.

2021-09-27 00:18 UTC, kotp approved these changes
Good find, sentences in bullets that do not complete the stem for sure need periods.

I like it.  (My approval means nothing, but may speed up an approval and merge, maybe.)

2021-09-27 00:46 UTC, kotp commented
If you are going to continue committing as you go, you may want to set this as draft, until you are ready for review.

2021-09-27 01:04 UTC, sieis commented
Good call; thanks! Still learning the ins and outs :)

2021-09-29 19:56 UTC, adilanchian requested changes
Added some things to tweak here! Thanks so much for this :)

2021-09-29 19:56 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_2/Lesson_1_Get_Your_Local_Ethereum_Network_Running.md
> +I'll explain certain things in-depth as needed (ex. how mining working, how smart contracts are compiled and run, etc) *but for now let's just focus on getting stuff running*.
Little miss here:

Can you change
`ex. how mining working, how smart contracts are compiled and run, etc` ->

`ex. how mining works, how smart contracts are compiled and run, etc.`

2021-09-29 19:56 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_2/Lesson_3_Compile_Contract_Locally.md
> +Be sure to make that console.log whatever you want! You've now written your own contract and run it by deploying to a local blockchain WOOOOOOOOOO LETS GOOO.
This is actually correct and should stay as `ran` :).

Please revert!

2021-09-29 19:56 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_2/Lesson_4_Store_Data_On_Smart_Contract.md
> +The blockchain = Think of it as a cloud provider, kinda like AWS. But, it's owned by no one. And, is run through compute power powered by random people called miners. We pay miners to run our code.
Can you change this to say:

```
The blockchain = Think of it as a cloud provider, kinda like AWS, but it's owned by no one. It's ran by compute power from mining machines all over the world. Usually these people are called miners and we pay them to run our code!
```

2021-09-30 00:49 UTC, sieis commented
@adilanchian I got those edits and reversions you mentioned fixed now, and addressed the few more typos I found going through the rest of the project.

2021-09-30 00:51 UTC, adilanchian approved these changes

2021-09-30 00:52 UTC, adilanchian commented
This is an EPIC change. Thanks for taking the time to add all these changes for us! Merging you in right now :)

2021-09-30 00:52 UTC, merged

2021-09-30 00:53 UTC, adilanchian commented
@all-contributors please add @sieis for doc

2021-09-30 00:54 UTC, sieis commented
You bet; happy to help, and I appreciate y'all putting this together!