Update: Added note on direct image links
zipeducation/buildspace-projects pull request #35
Opened 2021-09-27 05:45 UTC by AlmostEfficient

A couple of people used Imgur gallery links instead of direct image links, breaking their NFTs, as they appeared to not have an image.

I've added the following in section 2, lesson 4, right after the note to create their own metadata.

> If you decide to use your own image, make sure the URL goes directly to the actual image, not the website that hosts the image! Direct Imgur links look like this - `https://i.imgur.com/123123.png` NOT `https://imgur.com/gallery/123123`. The easiest way to tell is to check if the URL ends in an image extension like `.png` or `.jpg`.

2021-09-27 09:08 UTC, AlmostEfficient commented
Had two people ask about #course-chat, which does not exist in this cohort. Changed to #cowork-chat

2021-09-29 20:04 UTC, adilanchian requested changes
This is a great one. Just asking for a few changes :).

Thanks!

2021-09-29 20:04 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_2/Lesson_4_Store_Data_On_Smart_Contract.md
> +Why do we do a `waveTxn.wait();` though? What are we waiting for? Why didn't we do a `.wait()` after we read the total number of waves? Post your thoughts in the cowork-chat on Discord. Whoever gets
Can you actually change this to point to the `#general-chill-chat` channel please :)?

2021-09-29 20:04 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_2/Lesson_4_Store_Data_On_Smart_Contract.md
> +Check this out. I added a few lines at the bottom of the function. I'm not going to explain it much (but please ask questions in #cowork-chat). Basically this is how we can simulate other people hitt
Can you actually change this to point to the `#general-chill-chat` channel please :)?

2021-09-29 20:04 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_2/Lesson_5_Deploy_Locally.md
> +INTERESTING. But...what's gas? What does it mean by block #1? What's the big code next to "Transaction"? I want you try and just Google this stuff. Ask questions in #cowork-chat :).
Can you actually change this to point to the `#general-chill-chat` channel please :)?

2021-09-29 20:04 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +         * Let me know what you learn in #cowork-chat
Can you actually change this to point to the `#general-chill-chat` channel please :)?

2021-09-29 20:04 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +**Bonus**: In #cowork-chat, can anyone tell me some solutions here? Where else could we store our wave data where we could update our contract's code and keep our original data around? There are quit
Can you actually change this to point to the `#general-chill-chat` channel please :)?

2021-09-29 21:25 UTC, AlmostEfficient commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +         * Let me know what you learn in #cowork-chat
Updated :)

2021-09-29 21:25 UTC, AlmostEfficient commented on Solidity_And_Smart_Contracts/Section_2/Lesson_5_Deploy_Locally.md
> +INTERESTING. But...what's gas? What does it mean by block #1? What's the big code next to "Transaction"? I want you try and just Google this stuff. Ask questions in #cowork-chat :).
Updated :)

2021-09-30 13:40 UTC, adilanchian approved these changes

2021-09-30 13:40 UTC, merged

2021-09-30 13:41 UTC, adilanchian commented
Thank you again for your awesome changes! Great catches all around 🎉