Add missing ethers import and a semicolon
zipeducation/buildspace-projects pull request #39
Opened 2021-09-27 17:36 UTC by assimovt

2021-09-29 20:12 UTC, adilanchian requested changes

2021-09-29 20:12 UTC, adilanchian commented on NFT_Collection/Section_4/Lesson_3_Create_Button_To_Call_Contract.md
> +import { ethers } from 'ethers';
So this is isn't actually needed here!

In this snippet we are actually just trying to show the method to show here only! 

This should imported at the top of your file at the beginning :)

Would love for you to make a typo change for me though:

Can you change `Go ahead. and add the following function under the `connectWallet` function.` to `Go ahead and add the following function under the `connectWallet` function.`

2021-09-30 07:43 UTC, assimovt commented on NFT_Collection/Section_4/Lesson_3_Create_Button_To_Call_Contract.md
> +import { ethers } from 'ethers';
Gotcha, probly somewhere else you need to instruct to import ethers, otherwise, it was completely missing. Good catch on the typo, fixed 👍

2021-09-30 13:42 UTC, adilanchian approved these changes
Beautiful. Thank you for the changes!!

2021-09-30 13:42 UTC, merged

2021-09-30 13:42 UTC, adilanchian commented
@all-contributors please add @assimovt  for doc