Variable changes and Quality of Life improvements
zipeducation/buildspace-projects pull request #40
Opened 2021-09-27 19:05 UTC by FounderCasey

Hey _buildspace folks!

After finishing up the Solidity course, I've been helping folks out in the discord and I noticed there were some recurring issues.

Namely:
- Importing the `WavePortal.json` and calling it something other than the `contractABI`
- Adding more instruction on where to find the MetaMask private key
- Renaming `#course-chat` to `#cowork-chat`

2021-09-29 20:16 UTC, adilanchian requested changes
Sick stuff! Thanks so much :)

Added a few comments!

2021-09-29 20:16 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +        const waveportalContract = new ethers.Contract(contractAddress, contractABI, signer);
So this actually may prove to be a bit more confusing considering we are using `waveportal.abi` in other sections here.

If you still want to make this change, would you be open to verifying that this is corrected in any other spots in the code?

Thanks in advance!!

2021-09-29 20:16 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +**Bonus**: In #cowork-chat, can anyone tell me some solutions here? Where else could we store our wave data where we could update our contract's code and keep our original data around? There are quit
Can you change this to be `#general-chill-chat` please?

2021-09-29 21:54 UTC, FounderCasey commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +        const waveportalContract = new ethers.Contract(contractAddress, contractABI, signer);
Found another one in the last lesson - changed to `contractABI`. All references should be fixed

2021-09-29 21:55 UTC, FounderCasey commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +**Bonus**: In #cowork-chat, can anyone tell me some solutions here? Where else could we store our wave data where we could update our contract's code and keep our original data around? There are quit
Changed!

2021-09-29 22:11 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +        const waveportalContract = new ethers.Contract(contractAddress, contractABI, signer);
So this is almost there! 

You import the json file and call it `contractABI`, but you need to call the `.abi` property inside of it. Check out this lesson and search for: `waveportal.abi` and you will see what I mean:

https://app.buildspace.so/courses/CO02cf0f1c-f996-4f50-9669-cf945ca3fb0b/lessons/LE52134606-af90-47ed-9441-980479599350

2021-09-29 22:40 UTC, FounderCasey commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +        const waveportalContract = new ethers.Contract(contractAddress, contractABI, signer);
Okay, so Farza does it differently in his loom example - I'm assuming a PR changed how the text does it because now we have conflicting material. [loom](https://www.loom.com/share/ddecf3caf54848a3a01edd740683ec48)

---
Here's how the video sets it up. Now we're dealing with the same issue as before, where we have folks who do it the way Farza did in the loom but the text material is now different. 

### Current Text Material:

```
import contractABI from "./utils/WavePortal.json"

// Skip to init of getAllWaves() and wave()

const waveportalContract = new ethers.Contract(contractAddress, contractABI.abi, signer);

```
### Farza's Loom Example

```
import abi from "./utils/WavePortal.json"

// Skip to init of contractABI

const contractABI = abi.abi;

// Skip to init of getAllWaves() and wave()

const waveportalContract = new ethers.Contract(contractAddress, contractABI, signer);
```

I guess that leaves us with two options, either remove the loom or update that section("Getting ABI File Content") - thoughts? Happy to chat on discord as well if needed

2021-09-30 13:47 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +        const waveportalContract = new ethers.Contract(contractAddress, contractABI, signer);
You're absolutely insane. Thank you SO MUCH for bringing this up. 

Ya this is an interesting one to fix... 

I think the best approach here would be to follow the video example and keep it consistent. It's much harder to update that loom instead of text content like this.

Would love your feedback on this! Feel free to DM me in Discord as well if thats easier :)

2021-09-30 16:22 UTC, FounderCasey commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +        const waveportalContract = new ethers.Contract(contractAddress, contractABI, signer);
I think we're good here, most recent commit should fix this

2021-09-30 17:22 UTC, adilanchian requested changes
Small typo :)

2021-09-30 17:22 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_3/Lesson_4_Call_Deployed_Contract.md
> +Now that you have your file with all your ABI content ready to go, it's time to import it into your `App.js` file and create a refence to it. Right under where you imported `App.css` go ahead and imp
Small typo here :)

`reference`

2021-09-30 17:36 UTC, FounderCasey commented on Solidity_And_Smart_Contracts/Section_3/Lesson_4_Call_Deployed_Contract.md
> +Now that you have your file with all your ABI content ready to go, it's time to import it into your `App.js` file and create a refence to it. Right under where you imported `App.css` go ahead and imp
![](https://media3.giphy.com/media/l4Ep6uxU6aedrYUik/giphy.gif?cid=ecf05e478440mbeaqboc6dhizut3vd40s1umaeq8mjxoxhkc&rid=giphy.gif&ct=g)

2021-09-30 17:43 UTC, adilanchian approved these changes

2021-09-30 17:44 UTC, adilanchian commented
Y.E.S.

Thank you again for your time!!

2021-09-30 17:44 UTC, merged

2021-09-30 17:44 UTC, adilanchian commented
@all-contributors please add @FounderCasey for doc