Update wave txn variable name to avoid compiler errors
zipeducation/buildspace-projects pull request #42
Opened 2021-09-27 19:28 UTC by janndriessen

Another option would be to remove the let if `waveTxn` variable was to be reused.

I chose to just name it `waveTxn2` here.

2021-09-29 20:19 UTC, adilanchian requested changes

2021-09-29 20:19 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_5/Lesson_1_Randomly_Pick_Winner.md
> +  await waveTxn2.wait();
Since none of these properties are being re-written, could you change the `let`s to `const`s please :)?

2021-09-30 08:41 UTC, janndriessen commented on Solidity_And_Smart_Contracts/Section_5/Lesson_1_Randomly_Pick_Winner.md
> +  await waveTxn2.wait();
Makes sense. Fixed.

2021-09-30 13:50 UTC, adilanchian commented
Cheers 🎉🎉🎉

2021-09-30 13:50 UTC, merged

2021-09-30 13:50 UTC, adilanchian commented
@all-contributors please add @janndriessen for doc