Daeshawn issue 45 web3 app storing message in array typos
zipeducation/buildspace-projects pull request #46
Opened 2021-09-27 22:12 UTC by daeshawnballard

See the commit messages.

2021-09-28 00:38 UTC, kotp commented
Mentioning #45 here so it links not only the commits involved but this PR as well.

Don't forget to make a commit that addresses contractions as mentioned in the issue.

2021-09-29 20:22 UTC, adilanchian requested changes
Awesome!

Thanks for the contribution :). Just a small change please!

2021-09-29 20:22 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +3\. show that data on our site, so, anyone can come to see all the people who have waved at us and their messages.
Cool with removing the `Actually` here, but can you keep them capitalized at the start of the sentence?

2021-09-29 21:03 UTC, kotp commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +3\. show that data on our site, so, anyone can come to see all the people who have waved at us and their messages.
Because the bullet statements complete a sentence, it really should be lower case to allow for that.  It is technically not the start of the sentence.

2021-09-29 21:04 UTC, kotp commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +3\. show that data on our site, so, anyone can come to see all the people who have waved at us and their messages.
Of course, defer to @adilanchian as I am just an active observer, and they are a maintainer.

2021-09-29 21:15 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +3\. show that data on our site, so, anyone can come to see all the people who have waved at us and their messages.
Ya valid - I think in this instance though, it just looks cooler hehe

2021-09-29 23:28 UTC, kotp commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +3\. show that data on our site, so, anyone can come to see all the people who have waved at us and their messages.
If we do want them to be full sentences, we could make the stem of the bullet read:

`We will do these things at the end of the lesson:` which is a sentence ending statement, as it is ended with a colon, instead of a semi-colon which continues the sentence.  Then, complete sentences would be expected for each bullet, and that means capital letters to start off the sentence.

2021-09-30 13:52 UTC, adilanchian commented on Solidity_And_Smart_Contracts/Section_4/Lesson_1_Storing_Messages_From_Users.md
> +3\. show that data on our site, so, anyone can come to see all the people who have waved at us and their messages.
I appreciate the thoughts here!

I think we should just stick with capitalized first word :). It may not be 100% grammatically correct, but it's more aesthetically pleasing and I think thats fine!

2021-10-04 18:09 UTC, adilanchian commented
@daeshawnballard - any updates here? Lemme know else I can get this done! Thanks :)

2021-10-05 14:29 UTC, adilanchian commented
I went ahead and added some final touches. This is good to go!

2021-10-05 14:29 UTC, merged

2021-10-05 14:29 UTC, adilanchian commented
@all-contributors please add @daeshawnballard for doc