Avoid inline component definitions
zipeducation/buildspace-projects pull request #65
Opened 2021-09-30 11:13 UTC by JoviDeCroock

Generally the following is considered a bad practice as we are defining a functional component within the render-scope of the rendering component.

```
const App = () => {
  const renderGreeting = () => <p>hi</p>;
  return renderGreeting();
}

vs

const Greeting = () => <p>hi</p>;

const App = () => {
  return <Greeting />
}
```

This is a very subtile weirdness that has the same effect as using a different "key" prop on every render. The child diffing will look at the type of every vnode and see that the functional identity has changed which will mean that we'll tear the subtree down rather than doing an update on it. destroy + create instead of update on every render

2021-09-30 14:00 UTC, adilanchian commented
This is a **REALLY** cool PR. Thanks for submitting it. Some a couple thoughts around here - 

> Generally the following is considered a bad practice as we are defining a functional component within the render-scope of the rendering component.

^ This is definitely valid and something to be aware of, but given the complexity of this UI does this truly matter in this context? 

I think at the very minimum using something like `useCallback` may actually be a better approach! Caching this and only re-rendering on certain prop changes.

Essentially what you are doing is creating another functional component (is what I'm seeing at least!) Is it worth it for something this small?

Thanks again for the CodePen example! Super cool and I'm really excited to learn more from you about this.

2021-09-30 14:04 UTC, JoviDeCroock commented
@adilanchian it teaches a practice that will introduce a footgun for a lot of people in the future I feel 😅 I mean, I don't mind removing it but `useCallback` or `useMemo` are still invalid when it comes to a render context and will pose their own issues when it comes to a child-diffing algo

2021-09-30 14:12 UTC, adilanchian commented
@JoviDeCroock 10000% agree here. Definitely don't want to teach people the wrong approach here! Curious if you know of any React docs here that we could also point people to! I think it's important to show people the way, but hopefully they feel curious enough to explore it more and it would be cool to provide some resources for them :).

I am definitely fine with this change, just talking about the ways I usually approach this problem and I would love to understand more of when it makes sense to do something like this _OR_ generate a new component?

Thanks again!

2021-09-30 14:20 UTC, JoviDeCroock commented
That's a good question, so there are other valid ways of tackling this and I guess this is more a personal preference kind off thing, let me elaborate on my reasoning.

First let's look at an alternative approach that would work as well:

```
const App = () => {
  const renderNotConnectecd = useCallback(() => {
    const NotConnected = () => ...
    // Doing this in two steps so we don't lose our displayName and it actually has a name for react-refresh/react-devtools
    return NotConnected;
  }, [/* so here's the tricky bit, if we add "connectWallet" here then it still recreates the component as in the sandbox*/])
  
  return renderNotConnectecd()
}
```

A similar solution can be done with `useMemo` allthough it runs into a similar issue as elaborate in the deps array of our `useCallback`, do we really want to drop and recreate the component when a prop changes?

Then when there are no props this would be a valid approach but then we get to responsibilities, do we think this `NotConnected` ui-element is a responsibility of `App` if so we can scope it there but generally I'd think the answer (for me atleast) would be no as it's a separate component managing it's own little dom-elements.

I've been looking around but can't immediately find documentation around this but I can refer to a codebase where this becomes clear, in [Preact](https://github.com/preactjs/preact/blob/master/src/diff/children.js#L112) child diffing you can see that we match an oldVNode on _or_ a key _or_ a type, type refers to our function or a string value like `div`. When every render redefines this type these never matches which means we have to call unmount and remount.

2021-09-30 17:31 UTC, adilanchian commented
> do we really want to drop and recreate the component when a prop changes?

So for this this would only make sense if our button was changing in some way right? Essentially this button just needs to be shown or not shown so if wallet is not connected don't render this thing.

> Then when there are no props this would be a valid approach but then we get to responsibilities, do we think this NotConnected ui-element is a responsibility of App if so we can scope it there but generally I'd think the answer (for me atleast) would be no as it's a separate component managing it's own little dom-elements.

This is the biggest thing to me and thats why we came to this approach. The original setup of this is actually something I prefer to commonly do when I just want to place components in more "silo-ed" areas, but I don't see them being big enough to separate out into their own components

I guess what I'm trying to say -> **What would be the _best_ approach for a small project like this without over complicating it.** 

Would it make more sense to throw this button directly into the render method of the component and call it a day?

2021-09-30 17:32 UTC, JoviDeCroock commented
> Would it make more sense to throw this button directly into the render method of the component and call it a day?

I guess this is also a very valid solution 😅

2021-09-30 17:53 UTC, adilanchian requested changes
Added some thoughts here :)

2021-09-30 17:53 UTC, adilanchian commented on NFT_Collection/Section_4/Lesson_2_Connect_Wallet_To_Web_App.md
> +		</button>
Looks like there is a bit of weird spacing at the beginning here if you can fix please :)

2021-09-30 17:53 UTC, adilanchian commented on NFT_Collection/Section_4/Lesson_2_Connect_Wallet_To_Web_App.md
> +		</button>
Spacing here as well!

2021-09-30 17:53 UTC, adilanchian commented on NFT_Collection/Section_4/Lesson_3_Create_Button_To_Call_Contract.md
> +);
For this can you do the following - 

```
return (
 {currentAccount === "" ? (
     <button onClick={connectWallet} className="cta-button connect-wallet-button">
         Connect to Wallet
     </button>
   ) : (
      {/** Add askContractToMintNft Action for the onClick event **/}
      <button onClick={askContractToMintNft} className="cta-button connect-wallet-button">
         Mint NFT
      </button>
    )}
);
```

2021-10-04 18:12 UTC, adilanchian commented
Hey @JoviDeCroock - 

Let me know if you can get the rest of this in! If not I'll get it done :)

Thanks!

2021-10-04 18:18 UTC, JoviDeCroock commented
hey @adilanchian sorry about that, this went out of my mind

2021-10-04 19:30 UTC, adilanchian commented
No worries! this looks to have done the trick :). Thanks for this woot woot

2021-10-04 19:30 UTC, merged

2021-10-04 19:30 UTC, adilanchian commented
@all-contributors please add @JoviDeCroock for doc