Update from deprecated version of networkVersion
zipeducation/buildspace-projects pull request #66
Opened 2021-09-30 11:44 UTC by Espequair

https://docs.metamask.io/guide/ethereum-provider.html#ethereum-networkversion-deprecated indicates `ethereum.networkVerstion` is now deprecated.
I'm proposing we change it to the link I put, since I can't find another place it's explicit.

2021-09-30 14:05 UTC, adilanchian commented
Ya this is SICK - I feel like it may be worth pointing out here what they point out in the docs - 

`It's preferred to use the ChainID instead of the NetworkId` 

Maybe you can throw a little example of what this looks like and see if it works!!

Thoughts?

2021-09-30 14:05 UTC, adilanchian commented
cc @farzaa @DavidBarrick 

This is a cool one!

2021-09-30 17:53 UTC, Espequair commented
Sure, I'll get on it!

2021-09-30 19:26 UTC, DavidBarrick commented
I like. Shouldn't the link point here thought? https://docs.metamask.io/guide/ethereum-provider.html#chain-ids

2021-09-30 21:04 UTC, Espequair commented
That *should* be it. As to why I didn't just change the link to https://docs.metamask.io/guide/ethereum-provider.html#chain-ids, it's because it doesn't actually say how to fetch the chainID

2021-10-01 14:38 UTC, adilanchian requested changes
This is a great change! 

Left some comments for ya :)

2021-10-01 14:38 UTC, adilanchian commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +```js
Can you change this to be `javascript` please :). Our App Markdown reader like that instead hehe

2021-10-01 14:38 UTC, adilanchian commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +	alert("This website connects to a contract on the Rinkeby test network\nYour wallet is currently not connected to that network, so it won't work");
Can we just make this alert message say:

"You are not connected to the Rinkeby Test Network!"

Thoughts?

2021-10-01 14:38 UTC, adilanchian commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +The request conforms to [EIP-695](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-695.md) so returns the hex value of the network as a string.
Small typo here:

`...so it returns the hex value of the network as a string.`

2021-10-01 14:38 UTC, adilanchian commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +You can find other the IDs of the other networks on [here](https://docs.metamask.io/guide/ethereum-provider.html#chain-ids).
Small typo here:

`You can find IDs of other networks here`

2021-10-01 18:01 UTC, adilanchian requested changes
Couple more small things here!

2021-10-01 18:01 UTC, adilanchian commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +There, now the user will know if they're on the wrong network!
This should also be `their` and not `they're` btw :)

2021-10-01 18:01 UTC, adilanchian commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +You can find other the IDs of the other networks [here](https://docs.metamask.io/guide/ethereum-provider.html#chain-ids).
Can you change to `You can find IDs of other networks here!`

2021-10-02 00:11 UTC, Espequair commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +There, now the user will know if they're on the wrong network!
I'm actually pretty sure I'm right on this one. "They are on the wrong network"

Changed it to remove the contraction.

2021-10-02 00:12 UTC, Espequair commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +let chainID = await ethereum.request({ method: 'eth_chainId' });
`chain_Id` as it turns out. I changed every instance to make sure it was consitent.

2021-10-02 00:13 UTC, Espequair commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +You can find other the IDs of the other networks [here](https://docs.metamask.io/guide/ethereum-provider.html#chain-ids).
I swear I did my own proofreading pass first :(

2021-10-04 18:14 UTC, adilanchian requested changes

2021-10-04 18:14 UTC, adilanchian commented on NFT_Collection/Section_5/Lesson_1_Finishing_Touches_Web_App.md
> +if (chainId !== "0x4" /*String, hex code of the chain ID of the Rinkebey test network */ ) {
Hey so sorry - one more change here

Can you just add this comment on the line above the if statement?

2021-10-05 01:26 UTC, Espequair commented
Change done. I'm writing this comment mostly to test if github will let me change the status

2021-10-05 14:30 UTC, adilanchian commented
> Change done. I'm writing this comment mostly to test if github will let me change the status
> 
> **ETA:** No it won't, or at least there's another step I haven't discovered yet

Change the status? Hmmmm not quite sure what you mean here!

2021-10-05 14:33 UTC, adilanchian commented
@Espequair thank you for working with my changes here!!

I went in and tweaked just a few things! This is GOOD TO GO.

2021-10-05 14:34 UTC, merged

2021-10-05 14:34 UTC, adilanchian commented
@all-contributors please add @Espequair for doc